# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-05-26 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
